### ISSUE TITLE
Capture view as svg

### ISSUE THREAD

**Issue by gedw99** [ProjectSeptemberInc/gl-react#20]
This would only be applicable to 3d models that are hidden line views. Doing it with phong renderings, for example is too much work.

There is a common pattern where you need to capture a screen, but you also want to print. To print you need a vector representation.

I know this is a tough one, and I am asking for advice of how to do it, so I can try.

**Comment by gre** [comment]
I'm not sure to understand what you mean by "capture view as svg", right now we can capture the gl view as a PNG.

Also 3D models are currently out of scope of gl-react but discussion on supporting vertex data / vertex shader has been started: https://github.com/ProjectSeptemberInc/gl-react/issues/6

**Comment by gedw99** [comment]
hey @gre 
thanks for the info.

i need to do the same thing as you mentioned, capturing the gl view as a PNG, except i was hoping to capture it as SVG. SVG being a vector format.
Maybe this should be a new "want" for the issues ? Dont know what you think. With threejs its posible. It captures everything but not texture. So its technically possible.

Regarding 3D models, it seems your using a 3d webgl canvas, but the architecture is only designed for 2D operations ?  The 2D functionality is something i need, but it would be also useful to me (and maybe others) for  reactive 3D functionality too. Again i guess its up to you if you want to allow this featured as a possible thing to work on going forward.

I could help with some of the work, but i would be very curious what others also feel, because its a fair bit of work.

**Comment by gre** [comment]
There is no such thing as "3d webgl canvas". WebGL is a low level API, fundamentally [a 2D API](http://www.html5rocks.com/en/tutorials/webgl/webgl_fundamentals/), that allows you to implement incredible effects/draws and with the performance of the GPU. Of course you can do 3D with WebGL and this is what most people do with WebGL but our use-case is more wide than this:

`gl-react` is a thin wrapper on top of WebGL to use GL Shaders in React context and currently focus on making stack of effects. As being a thin wrapper, gl-react does not abstract WebGL so much, you have to write fragment shaders to do effects.

Also Canvas is fundamental a 2D pixels area. It is a bitmap and it is not vectorial as SVG is. Therefore I see no way to generically generate an SVG out of this.

Currently it does not implement vertex data / vertex shader which is needed for making polygons and therefore making 3D stuff. This is tracked in https://github.com/ProjectSeptemberInc/gl-react/issues/6 but it is not in our priority right now because the task is huge. Especially if we want to make it also for `gl-react-native`.

If you want to do more advanced 3D, I would recommend using Three.js in React, maybe via https://github.com/Izzimach/react-three . Any classical WebGL library can be used in React with a component that render() a `<canvas />` (see [Working with the Browser](https://facebook.github.io/react/docs/working-with-the-browser.html) ).

**Comment by gedw99** [comment]
Makes sense. Thanks for filling me  in, because i was not sure.

I will have a look at react.three, as yes it does sounds like more of what i am looking for. I did not know about that one.

Closing...
